"""Optimization utilities."""

from slam.optimization.bundle_adjustment import (
    BALObservation,
    BALProblem,
    BundleAdjustmentResult,
    bal_jacobian_sparsity,
    pack_bal_parameters,
    read_bal_problem,
    reprojection_residuals,
    reprojection_rmse,
    residuals_from_parameters,
    solve_bundle_adjustment,
    unpack_bal_parameters,
)
from slam.optimization.curve_fitting import CurveFitResult, exponential_curve, fit_exponential_curve
from slam.optimization.gtsam_backend import (
    OptionalBackendDependencyError,
    optimize_bundle_adjustment_gtsam,
    optimize_pose_graph_gtsam,
    require_gtsam,
)
from slam.optimization.pose_graph import (
    PoseGraph,
    PoseGraphEdge,
    PoseGraphOptimizationResult,
    PoseGraphVertex,
    edge_error,
    pack_pose_graph_parameters,
    pose_graph_residuals_from_parameters,
    read_g2o_pose_graph,
    solve_pose_graph,
    total_edge_error,
    unpack_pose_graph_parameters,
)

__all__ = [
    "BALObservation",
    "BALProblem",
    "BundleAdjustmentResult",
    "CurveFitResult",
    "PoseGraph",
    "PoseGraphEdge",
    "PoseGraphOptimizationResult",
    "PoseGraphVertex",
    "OptionalBackendDependencyError",
    "bal_jacobian_sparsity",
    "exponential_curve",
    "fit_exponential_curve",
    "edge_error",
    "pack_bal_parameters",
    "pack_pose_graph_parameters",
    "pose_graph_residuals_from_parameters",
    "optimize_bundle_adjustment_gtsam",
    "optimize_pose_graph_gtsam",
    "read_bal_problem",
    "read_g2o_pose_graph",
    "reprojection_residuals",
    "reprojection_rmse",
    "residuals_from_parameters",
    "require_gtsam",
    "solve_bundle_adjustment",
    "solve_pose_graph",
    "total_edge_error",
    "unpack_bal_parameters",
    "unpack_pose_graph_parameters",
]
